export const reducerCases = {
  SET_USER_INFO: "SET_USER_INFO",
  SET_NEW_USER: "SET_NEW_USER",
  SET_ALL_CONTACTS_PAGE: "SET_ALL_CONTACTS_PAGE",
  CHANGE_CURRENT_CHAT_USER: "CHANGE_CURRENT_CHAT_USER",
  SET_CURRENT_CHAT: "SET_CURRENT_CHAT",
  SET_MESSAGES: "SET_MESSAGES",
  SET_SOCKET: "SET_SOCKET",
  SET_SOCKET2: "SET_SOCKET2",
  ADD_MESSAGES: "ADD_MESSAGES",
  SET_ALL_GROUP: "SET_ALL_GROUP",
  SET_VIDEO_CALL: "SET_VIDEO_CALL",
  SET_VOICE_CALL: "SET_VOICE_CALL",
  END_CALL: "END_CALL",
  SET_INCOMING_VOICE_CALL: "SET_INCOMING_VOICE_CALL",
  SET_INCOMING_VIDEO_CALL: "SET_INCOMING_VIDEO_CALL",
  SET_SENT_INVITATION: "SET_SENT_INVITATION",
  SET_RECEIVE_INVITATION: "SET_RECEIVE_INVITATION"
};
